/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './_includes/**/*.{html,js}',
    './_layouts/**/*.{html,js}',
    './_posts/**/*.{html,md}',
    './_pages/**/*.{html,md}',
    './florida/**/*.{html,js}',
    './*.{html,js}',
  ],
  safelist: [
    'bg-white',
    'md:gap-4',
    'size-2',
    'size-3',
    'size-4',
    'size-5',
    'size-6',
    'text-orange-500',
    'w-screen',
    'justify-between',
    'text-base',
    'font-medium',
    'font-semibold',
    'inline-flex',
    'opacity-75',
    'mb-0',
    'ml-2',
    'mt-0',
    'pt-2',
    'pb-4',
    'gap-4',
    'lg:flex',
    'md:grid-cols-3',
    'bg-slate-900',
    'text-white',
    'hidden',
    '!hidden',
    'min-h-[44px]',
    'animate-pulse',
    'rounded',
    'bg-gray-300',
    'w-16',
    'h-5',
    'mt-1',
    'md:items-center',
    'md:w-auto',
    'md:gap-2',
    'text-[15px]',
    'md:text-base',
    'md:mx-0',
    'md:px-0',
    'justify-center',
    'py-8',
    // You can also use patterns
    // 'bg-[0-9]+',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
} 